### ISSUE TITLE
Add more activation functions 

### ISSUE THREAD

**Issue by jeveley** [PSZT16Z/NeuralFunc#10]
Pass indicators of function type to restructure method as a matrix (for each neuron)

**Comment by mkulagowski** [comment]
I would choose them via string argument, that works via dictionary. Moreover imo it should be chosen per Neural Network instance, not per each neuron.

Our sigmoid derivative is wrong - it should be:
sigmoid(x)' = sigmoid(x) * (1 - sigmoid(x))

As per different activation functions, we can take them e.x. from [here](https://en.wikipedia.org/wiki/Activation_function).
Tanh:
tanh(x) = np.tanh(x)
tanh(x)' = 1 - (tanh(x)^2)

and maybe linear? like:
lin(x)=x
lin(x)'=np.ones_like(x)

**Comment by jeveley** [comment]
He explicitly said that usually activation function is passed as a matrix, one for each neuron ;/ I will try to  find examples of this, to check that it really is a common practice.

**Comment by mkulagowski** [comment]
After talking with lecturer we finally have clear idea what should be done.
Arguments for creating NN should be:
- number of inputs `Integer; >0`
- number of neurons in hidden and outer layers `array<Integer>; each >0, len()>0`
- activation functions used in hidden and outer layers `array<char>; each should be taken from dict, default should be chosen by us, (len()==0 || len()==len(arg2))`

In 3rd arg I would do it like so:
- dict containing char->callback
- based on input `array<char>` I would fill out `array<callback>`
- if `len()==0`, then default `array<callback>` would be created
- if `len()==number of hidden/outer layers`, then we have 2 possibilities
  - char is in dict, add proper callback to our array
  - char is invalid, in this case add default callback for current layer (note that we will have different default callback for hidden and for outer layer)

Whaddya think?

**Comment by mkulagowski** [comment]
Actually a lot has changed...and it probably will continue to change.
I've fixed sigmoid function, added tanh & identity functions and instead of 3 arguments we still have one - a list of tuples consisting of number of neurons in each layer & an activation function used for it.
First number from the list is number of inputs, last one is the outer layer & the rest are hidden layers.
