### ISSUE TITLE
Updating learning rate through UI

### ISSUE THREAD

**Issue by jeveley** [PSZT16Z/NeuralFunc#6]
Consider: does NN needs to be reset after updating?

**Comment by mkulagowski** [comment]
IMO nope. Learning rate just scales changes made to neurons, so reset shouldn't be obligatory here.

We could implement method that resets only neurons, so that NN starts to adapt anew - making this separate from learning rate change, dataset, etc makes it much more usable.

**Comment by mkulagowski** [comment]
Done by @jeveley
